"""Aggregate individual changes/ entries into changes_log.yaml.

Run from repo root after adding a new changes/YYYY-MM-DD-slug.yaml::

    python scripts/aggregate_changelog.py

This rewrites changes_log.yaml with all entries sorted by (date, version).
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).parent.parent
CHANGES_DIR = REPO_ROOT / "changes"
OUTPUT = REPO_ROOT / "changes_log.yaml"

HEADER = """\
# finplan-config change log
#
# Machine-readable record of every config and code change.
# Downstream repos (finplan-compute-engine, finplan-api-gateway) should use
# finplan_config.changelog to detect breaking changes on version upgrade:
#
#   from finplan_config.changelog import has_breaking_changes_since
#   if has_breaking_changes_since("2024.1.0"):
#       raise RuntimeError("finplan-config has breaking changes — review before upgrading")
#
# DO NOT edit this file directly — edit individual files under changes/ instead,
# then regenerate with: python scripts/aggregate_changelog.py

"""


def main() -> int:
    entry_files = sorted(CHANGES_DIR.glob("*.yaml"))
    if not entry_files:
        print("No entries found under changes/ — nothing to aggregate.")
        return 0

    entries = []
    for path in entry_files:
        with open(path) as f:
            entry = yaml.safe_load(f)
        if not isinstance(entry, dict):
            print(f"WARNING: {path.name} did not parse as a dict — skipping")
            continue
        # Ensure required fields
        for field in ("version", "date", "type", "summary"):
            if field not in entry:
                print(f"ERROR: {path.name} missing required field '{field}'")
                return 1
        # Normalise optional fields
        entry.setdefault("affected_configs", [])
        entry.setdefault("downstream_action_required", False)
        entry.setdefault("notes", "")
        entries.append(entry)

    # Sort by (date, version)
    entries.sort(key=lambda e: (str(e["date"]), str(e["version"])))

    document = {"schema_version": 1, "entries": entries}
    yaml_text = yaml.dump(document, default_flow_style=False, allow_unicode=True, sort_keys=False)

    OUTPUT.write_text(HEADER + yaml_text)
    print(f"Wrote {len(entries)} entries to {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
